//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPackage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpBacklink
    {
        public int Id { get; set; }
        public string LinkType { get; set; }
        public string LinkUrl { get; set; }
        public string Description { get; set; }
        public System.DateTime LinkExpiry { get; set; }
        public string Status { get; set; }
    }
}
