//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPackage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpProdRate
    {
        public int Id { get; set; }
        public int tpProductsId { get; set; }
        public int tpUomId { get; set; }
        public int GroupOf { get; set; }
        public decimal Rate { get; set; }
        public string Remarks { get; set; }
        public int Sort { get; set; }
    
        public virtual tpProducts tpProduct { get; set; }
        public virtual tpUom tpUom { get; set; }
    }
}
