//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPackage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpProductDesc
    {
        public int Id { get; set; }
        public int tpProductsId { get; set; }
        public string tpDescH1 { get; set; }
        public string tpDescH2 { get; set; }
        public string tpDesc { get; set; }
        public int Sort { get; set; }
    
        public virtual tpProducts tpProduct { get; set; }
    }
}
